### ISSUE TITLE
Predicate in slotless item handler for insertion and extraction

### ISSUE THREAD

**Issue by raoulvdberge** [CyclopsMC/CommonCapabilitiesAPI#1]

**Comment by rubensworks** [comment]
Ok, I remember again what my reason was for not including a predicate for insertion and extraction.
The reason is that a predicate is _too_ generic, it doesn't allow the capability exposer to do any kind of indexing.

Let's say we would have the method `extractItem(Predicate<ItemStack>, boolean)`.
This requires the item provider to go over all items in its inventory, because it has no real knowledge about what is going on inside the predicate.
That is why I used the `ItemStack` with the different flag options, because this allows the provider to identify the `Item`, and possibly the damage value, NBT tag and stack size to match by.


I also don't think it would be a good idea to add a match flag for the oredictionary. Because the items having the same oredict key may be completely different, which again takes a way a lot of indexing power from the provider.

Alternatively, a consumer could do some wrapping like this when oredict matching is required (untested code):
```
for (String key : OreDictionary.getOres(itemStack)) {
    for (ItemStack oreStack : OreDictionary.getStacks(key)) {
        if (handler.extractItem(oreStack, ItemMatch.DAMAGE | ItemMatch.NBT, true)) {
            return handler.extractItem(oreStack, ItemMatch.DAMAGE | ItemMatch.NBT, false);
        }
    }
}
```
But I don't believe this should be added to the API here, for the sake of keeping the interface as simple as possible.

**Comment by raoulvdberge** [comment]
I didn't mean a `extractItem(Predicate<ItemStack>, boolean)`, I meant a `extractItem(ItemStack, Predicate<ItemStack>, boolean)`. That way, you still know what item to get.

**Comment by rubensworks** [comment]
@raoulvdberge `extractItem(Item, Predicate<ItemStack>, boolean)` would probably make more sense in your case then.
But this still takes a way a lot of indexing power from the item provider, i.e. it can not index by metadata, NBT and stacksize anymore, which is possible with the current match flags.

The main problem is that the provider is unable to know what exactly is needed when using black-box predicates, while the current flags actually form a white-box predicate, which is much better IMO, and as expressive.

The more I think about it, the more I am convinced that the current interface is the ideal one. It is simple and gives a lot of power to the provider to implement efficient indexing strategies. While at the same time, anything can be done by the consumer for retrieval and insertion, but possible multiple (very cheap) interface calls need to be done.

@raoulvdberge Are there any specific cases that you are unable to handle with the current interface?

**Comment by raoulvdberge** [comment]
We are trying to do this in a clean way here, we have already added so much hooks in the code to support this that I'm not honestly not happy with not having proper predicate filtering.

**Comment by rubensworks** [comment]
I agree that a predicate is cleaner, but the alternative allows for better performance.
In this case, the latter is the priority, as current TPS issues show.
So the current approach with match flags, which is less clean, but enables better performance is the obvious choice here IMO.

**Comment by raoulvdberge** [comment]
The perf impact isn't *that* bad of having a predicate.

**Comment by rubensworks** [comment]
Yes it is, the performance impact can be _very_ significant.

When an item provider for instance does indexing on `Item` and damage value, lookups by that can in `O(1)`. While a predicate, which only allows indexing by `Item`, will have a complexity of `O(n)`, with `n` being the maximum number of stored entries per `Item`, because of the required looping.

And that's only by taking into account damage values, there are other flags as well that can be considered.

**Comment by raoulvdberge** [comment]
I know that, what I'm getting to is that `n`, in a typical use case, isn't that big.

**Comment by rubensworks** [comment]
That's the whole point of this interface, to handle atypical use-cases efficiently as well.

For this specific case, there could be a (colossal) chest that is filled with stacks that all share the same `Item`, but have a different damage/nbt value, in that case `n` will be very large.
I think this case could occur frequently in real cases, where such a chest could be used as a buffer for such item variants.

The number of slots in a typical inventory isn't that big as well, but this is modded MC, so there will always be mods that to atypical things (e.g. Colossal Chests).

But ok, I have the feeling this discussion is going nowhere.
@raoulvdberge Can you work with this interface or not? If not, please provide an alternative that doesn't involve a black-box predicate and still allows efficient inserts/extracts through indexing.

**Comment by asiekierka** [comment]
For pretty much every use case, having a Predicate **equals** going through every slot by hand. It's silly, you can do it with just an IItemHandler - perhaps with slightly faster iteration.

**Comment by rubensworks** [comment]
The updated [`ISlotlessItemHandler`](http://cyclopsmc.github.io/CommonCapabilities/org/cyclops/commoncapabilities/api/capability/itemhandler/ISlotlessItemHandler.html) should provide a good trade-off in terms of expressivity and implementation complexity. Predicate-based filtering can be implemented on top of this using the `Iterator`-based methods.
